# Generated by Django 5.2.7 on 2025-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
